### ISSUE TITLE
Detect if wireguard tools are installed

### ISSUE THREAD

**Issue by aequitas** [aequitas/macos-menubar-wireguard#10]
Currently the app silently fails if WireGuard is not installed. Until WireGuard binaries are bundled provide better UX by detecting if tools are installed and provide error/instructions if they are not.

**Comment by eecharlie** [comment]
Suggest taking the additional step of auto-installing (or instructions to install) Homebrew if it's not installed.

And/or, have you considered packaging this as a homebrew formula in anticipation of contributing a stable version to the homebrew repository?

**Comment by aequitas** [comment]
I intend to do it the other way around. Bundle wireguard with the app so homebrew would not be needed at all. But for the MVP instructions to install will suffice.

**Comment by aequitas** [comment]
fixed in: https://github.com/aequitas/macos-menubar-wireguard/releases/tag/1.9
