### ISSUE TITLE
App crashes on MacOS Sierra

### ISSUE THREAD

**Issue by JSti** [aequitas/macos-menubar-wireguard#12]
The app seems to crash right after I try to start the app. Got the following in the log:

```
com.apple.xpc.launchd[1] (WireGuardStatusbar.88256[58280]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0]
com.apple.xpc.launchd[1] (com.apple.ReportCrash[58281]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
```

File permission are set:
```
# ls -al /usr/local/etc/wireguard/wg0.conf
-rw-r-----  1 user  staff  306 Dec 10 11:44 /usr/local/etc/wireguard/wg0.conf
```

I am (still) using MacOS Sierra. I don't see an OS requirement, but perhaps that has something to do with it.

**Comment by aequitas** [comment]
Hi @JSti,

thanks for reporting. I haven't put in a requirement as I don't know what is required to be honest :). I'll investigate this soon, if its feasible to support Sierra I will do so.

Could you maybe provide debug logs by using the "Console" app in `/Applications/Utilities/`, in it search for wireguard and then run the application so it generates logging.

**Comment by JSti** [comment]
Thank you for the effort looking into this. Not much in the Console app unfortunately, but here you go:

```
default	12:33:26.575030 +0100	WireGuardStatusbar	Helper: Bundle Version => 1.0.5
default	12:33:26.585566 +0100	WireGuardStatusbar	XPC Connection Invalidated
default	12:33:33.512207 +0100	authd	Succeeded authorizing right 'com.apple.ServiceManagement.blesshelper' by client '/Applications/WireGuardStatusbar.app' [58535] for authorization created by '/Applications/WireGuardStatusbar.app' [58535] (13,0)
default	12:33:44.544521 +0100	WireGuardStatusbar	Helper: Bundle Version => 1.0.5
default	12:33:44.552002 +0100	WireGuardStatusbar	XPC Connection Invalidated
default	12:33:48.545534 +0100	authd	Succeeded authorizing right 'com.apple.ServiceManagement.blesshelper' by client '/Applications/WireGuardStatusbar.app' [58542] for authorization created by '/Applications/WireGuardStatusbar.app' [58542] (13,0)
default	12:34:05.644820 +0100	WireGuardStatusbar	Helper: Bundle Version => 1.0.5
default	12:34:18.305359 +0100	WireGuardStatusbar	Helper: Bundle Version => 1.0.5
default	12:34:31.399265 +0100	WireGuardStatusbar	Helper: Bundle Version => 1.0.5
```

The authentication entries are logged when the install helper tool popup appears. Somehow it keeps asking about installing it after the first time, but not always. Weired.

I will try on a Mojave machine as well soon.

**Comment by JSti** [comment]
Just tried on Mojave:

`com.apple.xpc.launchd[1] (WireGuardStatusbar.7040[3340]): Service exited due to SIGILL | sent by exc handler[3340]`

I attached the console log and crash report.

[Wireguard_Mojave_crash_log.zip](https://github.com/aequitas/macos-menubar-wireguard/files/2668290/Wireguard_Mojave_crash_log.zip)

**Comment by JSti** [comment]
Just tried out Release 1.8 on Mojave but also crashes unfortunately.

**Comment by aequitas** [comment]
I'll have someone with Mojave test it as well to be sure if it is a OS specific error. 

From what I can tell it might have to do with optimizations that are turned on (by default) for just macOS 10.13 but I will have to investigate that later today. Don't know why it also crashed on on 10.14 as I would expect it to be backwards compatible.

I also noticed in the crash report that SIP is disabled on your machine. Don't know if that might be a factor?

**Comment by JSti** [comment]
Not sure, but it would surprise me. 

Perhaps there is something wrong with permissions somewhere, reading Wireguard config files for instance or something else. You might be able to do some error checking and handling and inform the user about files not able to read?

After futher testing on Mojave it seems it starts (with obviously no available configs found) correctly if Wireguard is not installed. I install Wireguard using brew. After that it crashes. Perhaps brew installs/configures things a bit different from what you expect?

`# brew install wireguard-tools`
`# wg-quick up wg0`

With config file located in: /usr/local/etc/wireguard/wg0.conf

`# ls -al /usr/local/etc/wireguard/wg0.conf`
`-rw-r-----  1 user  staff  306 Dec 10 11:44 /usr/local/etc/wireguard/wg0.conf`

**Comment by JSti** [comment]
`/etc/wireguard` does not exist, `/usr/local/etc/wireguard` is world readable.

**Comment by JSti** [comment]
Default permissions:
`# ls -al /var/run/wireguard`
`srwx------   1 root  daemon    0 Dec 11 16:52 utun1.sock`
`-r--------   1 root  daemon    6 Dec 11 16:52 wg0.name`
Directory is world readable/accessable by default.

Application still crashes after changing permissions to:
`srwxr-xr-x   1 root  daemon    0 Dec 11 16:52 utun1.sock`
`-r--r--r--   1 root  daemon    6 Dec 11 16:52 wg0.name`

**Comment by aequitas** [comment]
My guess would be then that it might hit a problem here: https://github.com/aequitas/macos-menubar-wireguard/blob/master/WireGuardStatusbar/AppDelegate.swift#L62 When adding the directories to the watchlist. But its just a wild guess. I haven't been able to make much sense of the crashreport/log.

I'll make a build with some more debug logging later today so we could get to the bottom of this if you want.

**Comment by JSti** [comment]
Sure I can run a debug build if that helps you to narrow down things.

**Comment by aequitas** [comment]
Can you try this version and provide the output from Console.

[WireGuardStatusbar.dmg.zip](https://github.com/aequitas/macos-menubar-wireguard/files/2672773/WireGuardStatusbar.dmg.zip)

**Comment by aequitas** [comment]
Alternatively you could try this build which has the build OS version aligned and set to 10.10. This does not contain the debug logging the previous build has.

[WireGuardStatusbar-d07d62d.zip](https://github.com/aequitas/macos-menubar-wireguard/files/2673156/WireGuardStatusbar-d07d62d.zip)

**Comment by JSti** [comment]
I attached the log file for this version. I think this part might be relevant:

`default	10:23:31.310724 +0100	WireGuardStatusbar	Reading config file: /usr/local/etc/wireguard/wg0.conf`
`info	10:23:31.516447 +0100	opendirectoryd	PID: 19426, Client: 'WireGuardStatusbar', exited with 0 session(s), 0 node(s) and 0 active request(s)`

Contents (keys and IP removed):

```
[Interface]
Address = 10.10.101.123/24
ListenPort = 51824
PrivateKey = X

[Peer]
PublicKey = X
Endpoint = 123.456.789.123:12345
#AllowedIps = 0.0.0.0/0
AllowedIps = 125.125.125.125/24, 123.123.123.123/24

PersistentKeepalive = 25
```

If I completely empty the file (no content, existing file) the app stops crashing. I also tried removing the commented line only but that does not stop the app from crashing. Rest are valid configuration entries.

[wireguardstatusbar_crash_20181213.txt](https://github.com/aequitas/macos-menubar-wireguard/files/2675311/wireguardstatusbar_crash_20181213.txt)

**Comment by aequitas** [comment]
Thanks this is probably enough information to research the issue from here. I'll get back to you later today.

**Comment by aequitas** [comment]
I was to lazy on the config reading error handling. The config file you have has a case difference in `AllowedIps` (compared to `AllowedIPs`) which crashed the app.

The latest release (https://github.com/aequitas/macos-menubar-wireguard/releases/tag/1.11) contains the fix to prevent the crash. You will be missing some info in the menu's but everything should work for the rest. Proper reading of the config contents will be fixed when I move it to the Helper.

**Comment by JSti** [comment]
Great, this fixes the crash problem and it's working now.

It seems WireGuard does not care about the wrong capitalization, nevertheless I corrected it so everything shows up properly in the app.

Thanks for your effort figuring this out and this great tool! 
Now time to add some extra statistics? Like traffic, uptime 😄

**Comment by aequitas** [comment]
Yw, good to hear it works for you and thanks for helping me investigate. I'll fix the issue with the casing at a later point. Tunnel stats is on the roadmap for a later point, but feel free to open a issue for that to share your ideas. I'm gonna close this one now as it is resolved.
