### ISSUE TITLE
Allow path to wg-quick to be specified.

### ISSUE THREAD

**Issue by dsully** [aequitas/macos-menubar-wireguard#15]
I have a small patch to wg-quick (That I'm trying to get upstream) to support DNS Search Servers.

It'd be nice to be able to chose the path to wg-quick, in case it is not in /usr/local/bin/

**Comment by aequitas** [comment]
Quickest solution for now would be to build the app yourself and changing: https://github.com/aequitas/macos-menubar-wireguard/blob/master/Shared/Const.swift#L19

I still need to figure out how to best provide dynamic configuration to the Privileged Helper (the part of the application running as root) as it would be a huge attack vector if just any binary path could be executed by a unprivileged user. So a proper implementation of this feature might take a while. I'm also investigating the possibility to provide wireguard with the app and ditching wg-quick as a whole.

**Comment by aequitas** [comment]
@dsully can you try if this works for you: https://github.com/aequitas/macos-menubar-wireguard/releases/tag/1.16

**Comment by dsully** [comment]
Yep, works great. Thanks!
