### ISSUE TITLE
Support Mullvad auto-generated configurations

### ISSUE THREAD

**Issue by eecharlie** [aequitas/macos-menubar-wireguard#2]
Hi,

[Mullvad](https://mullvad.net/en/guides/wireguard-mullvad-macos/) is one of a few commercial VPN providers that supports WireGuard.

They have a configuration setup script that dumps a bunch of named configuration files in /etc/wireguard/, of the form "mullvad-<ServerName>.conf". If these could be auto-detected and populated into the AppIcon dropdown menu, that would be awesome.

I did a quick and dirty test by moving the files from /etc/wireguard/ to /usr/local/etc/wireguard/ where your program looks, and found that the program hangs on startup (icon never appears, but Helper is left running in the background)

Further, if this were implemented I imagine Mullvad would consider using your tool as a recommended process for using WireGuard to connect to their service on MacOS.

**Comment by eecharlie** [comment]
Thanks so much!

I'm still getting a crash if the files in /usr/local/etc/wireguard aren't readable

The app does not crash if those files are group readable (admin group), and further works roughly as expected (I can switch to a new configuration). The app icon color doesn't seem to reflect wireguard connectivity, possibly due to a zombie configuration leftover from my attempt to launch wireguard with a .plist file.

Can you point to a quick ref on building Swift applications? I just installed Xcode..

**Comment by aequitas** [comment]
`/etc/wiregaurd` should be checked as well (https://github.com/aequitas/macos-menubar-wireguard/blob/master/Wireguard%20Statusbar/AppDelegate.swift#L37) so I'm curious why this doesn't work in your case, is the directory itself readable? (`ls -la /etc/wireguard/`).

I tried to implement sorting a while back (https://github.com/aequitas/macos-menubar-wireguard/blob/master/Wireguard%20Statusbar/AppDelegate.swift#L167) but I think Swift does not keep dict entries sorted, so I think thats why it doesn't work. I will move this logic somewhere else. I just hit this myself recently when I added more configs.

Building your own binary should be easy. Just run `make` in the project directory. You might need to update certificates/team id in the project settings to your own, as the app needs to be signed to be allowed to install the Helper. I think Xcode warns about this if you try to build it. But I'm not yet that familiar with that part myself.

Other features I have planned for the short term are 

- Option-click the icon so it only shows the details that way (like the WiFi icon does) and the menu when clicked normally is more terse (like it is now for the config files that cannot be read).
- Adding a icon state which indicates the different between tunnels being enabled and tunnels that are actually running/connected.

If you have any further feedback let me know, feel free to open Github issues for separate problems.

**Comment by eecharlie** [comment]
You are right, I posted the last comment without going back and checking whether `/etc/wireguard` was checked.

I got Xcode working with a configured dev account. Having issues with Makefile and with running app via Xcode that I'll open another issue on.

I will close this issue as you have resolved it. I may open another regarding menu sorting :)
