### ISSUE TITLE
Adding to Users -> Login item causes graphical glitch

### ISSUE THREAD

**Issue by annabel82** [aequitas/macos-menubar-wireguard#20]
Hi there, first of all great work; using it daily,

I have added WireGuardStatusbar 1.11 to Login Items under my user account with 'Hide' ticked. When I try and connect to a known good wireguard interface the icon top right of my screen doesn't change and I don't get a tick next to the interface I selected, however the connection IS connected and workiing.

If I close the app (not connection) and re-open it the the correct interface is ticked and the Icon top right correctly shows the connected Icon of a white circle with dark wireguard logo (I'm using Mojave dark mode).

Thanks

**Comment by annabel82** [comment]
Thanks for the reply :)

I have tried 1.14 after running 1.11's Uninstall.sh at terminal to remove old version. Same behavour as 1.11 I'm afraid.

**Comment by aequitas** [comment]
I've been able to replicate the behaviour on High Sierra with 1.14 as well. I don't restart my mac that often so this bug slipped under the radar. I don't have a clear cause at the moment. My guess still is some sandboxing or maybe some race condition with the Helper. Whats weird is that the commands can be sent to the helper to change tunnels but the helper is not able to sent a signal back to update. But I'll continue debug this on my end and get back when I've found a solution.

**Comment by aequitas** [comment]
I think I found the issue: `/var/run/wireguard/` does not exist after boot when the Helper tries to register the directory to watch for changes. So the Helper is never able to respond to changes in tunnel state. I'll have a fix for this out later today.

**Comment by annabel82** [comment]
Wow that was fast thanks ever so much :)

**Comment by aequitas** [comment]
Should be fixed now in: https://github.com/aequitas/macos-menubar-wireguard/releases/tag/1.15

Thanks for finding this bug, since `/var/run/wireguard/` always existed on my machine I never noticed this. For first time users this bug would also occur if WireGuard was never run.

**Comment by annabel82** [comment]
I installed 1.15 and rebooted and the glitch is gone thank you! :)
