### ISSUE TITLE
Menu bar opening bug

### ISSUE THREAD

**Issue by adamluk** [aequitas/macos-menubar-wireguard#22]
Sometimes the menu bar opens to the left of the icon. I can trigger this by connecting then disconnecting and then pressing the icon again. It doesn't always happen though. Please see the screenshot below. On Mojave 10.14.3

![screenshot 2019-01-29 at 12 05 13](https://user-images.githubusercontent.com/9057461/51907355-737f6d00-23be-11e9-952c-94ac222fa8c3.png)

![screenshot 2019-01-29 at 12 08 18](https://user-images.githubusercontent.com/9057461/51907430-b04b6400-23be-11e9-85a7-a2e330e77627.png)

Please let me know if you need any more information?

**Comment by aequitas** [comment]
This should have already been solved in the latest release: https://github.com/aequitas/macos-menubar-wireguard/releases/tag/1.23

Let me know if you experience this problem with this version as well.

**Comment by adamluk** [comment]
> This should have already been solved in the latest release: https://github.com/aequitas/macos-menubar-wireguard/releases/tag/1.23
> 
> Let me know if you experience this problem with this version as well.

I am using 1.23 - sorry, should have said.

**Comment by aequitas** [comment]
The problem is the menu positioning does not account for a change in width when the menu is dynamically updated (eg: tunnel details are added/removed after connect/disconnect).

So when the tunnel is connected there probably is one line of details that makes the menu really wide. Can you tell me which one, or show a screenshot (you can blur the details themselves)?

**Comment by aequitas** [comment]
I'll split the address over multiple lines then. I think that would work best. For other lines that could be long (like allowed IP's) I've adopted ellipses. But for this line splitting probably makes more sense. I'll try to get a fix out this week.
