### ISSUE TITLE
Update Homebrew Cask

### ISSUE THREAD

**Issue by xdays** [aequitas/macos-menubar-wireguard#23]
Hi aequitas,

Would you mind update the version in this cask file when you have a new release? I have submitted a PR https://github.com/Homebrew/homebrew-cask/pull/58145 for this awesome app. BTW, you may not know many people from China start using wireguard as another way to go through GFW. 👍 Thanks!

**Comment by aequitas** [comment]
Sure, I'll see if I can work that into the release scripting.

It would make sense to include `wireguard-tools` itself as a dependency for this cask I think as it is useless without WireGuard installed?
