### ISSUE TITLE
Can't mount WireGuardStatusbar-1.24-131.dmg on OSX 10.11.4

### ISSUE THREAD

**Issue by 5panky** [aequitas/macos-menubar-wireguard#26]
Sorry if this isn't the right place to query this.

Can't open the .dmg file, getting a message 'no mountable file system'

Did some searching and found the error (112) comes about becuase macOS Sierra (10.12) and earlier is not able to mount the new Apple File System (APFS)

Any chance of an image that will work with my older OS ?

Thanks,
Shane.

**Comment by aequitas** [comment]
This is the right place, thanks for reporting this issue.

Can you try this file: [WireGuardStatusbar-1.24-117.dmg.zip](https://github.com/aequitas/macos-menubar-wireguard/files/4185739/WireGuardStatusbar-1.24-117.dmg.zip)

If this works I'll update the release process to maintain compatibility with older OS releases.

**Comment by 5panky** [comment]
That worked just fine.
Thanks for looking at this so quickly, much appreciated.

**Comment by aequitas** [comment]
No problem, glad to help.
