### ISSUE TITLE
Sort config files alphabetically

### ISSUE THREAD

**Issue by eecharlie** [aequitas/macos-menubar-wireguard#5]
As [discussed](https://github.com/aequitas/macos-menubar-wireguard/issues/2#issuecomment-444688697) in #2 , there is no useful sort order when config file names are used to populate the status menu.

Please sort status menu by config file, alphabetically.

**Comment by aequitas** [comment]
Should be fixed in: https://github.com/aequitas/macos-menubar-wireguard/releases/tag/1.8
